// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://cyhrjnsjmqagxecexnea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aHJqbnNqbXFhZ3hlY2V4bmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDg2NDQsImV4cCI6MjA3MDY4NDY0NH0.VrKfTH2Xwd6VDXUVmNtsXYgYwjDfmpcNGfbBQTV2tlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});